version: "3"

services:
  pgdb:
    image: postgres
    container_name: postgres-container
    restart: unless-stopped
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./pgdb_volume:/var/lib/volumes/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: products
  
  node_server:
    container_name: node-container
    build: .
    image: pg_node:v1
    ports:
      - 5000:5000
    expose:
      - 5000
    restart: always
    environment:
      PG_HOST: pgdb
      PG_USER: postgres
      PG_PASS: postgres
      PG_DB: products
      PG_PORT: 5432
      NODE_OPTIONS: --max_old_space_size=8192
    depends_on:
      - pgdb
