name: Testing Vanilla Node.js
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PG_HOST: localhost
  PG_USER: postgres
  PG_PASS: postgres
  PG_DB: products
  PG_PORT: 5432

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: products
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: run unit test
        run: npm test

      - name: run the init.sql script
        run: |
          PGPASSWORD=postgres psql -U postgres -h 127.0.0.1 -p 5432 -d products -a -f init.sql

      - name: start node server and run integration test
        run: npm run start:dev & npm run itest
